version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.webserver_compress.compress=true"
      - "traefik.http.routers.webserver.middlewares=webserver_compress"
      - "traefik.http.routers.nginx.rule=Host(`nginx.$MY_DOMAIN`)"
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    hostname: traefik
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
networks:
  default:
    external:
      name: $DEFAULT_NETWORK