version: '3'

services:
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    hostname: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "80:80"
  nginx:
    image: "nginx:latest"
    container_name: "promenkul"
    hostname: "www.promenkul.org"
    restart: unless-stopped
    volumes:
      - ./nginx:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.http.routers.nginx.rule=Host(`www.promenkul.org`)"
      - "traefik.http.middlewares.test-compress.compress=true"
      - "traefik.http.middlewares.promenkul_compress.compress=true"
      - "traefik.http.middlewares.promenkul_compress.compress.minresponsebodybytes=200"
      - "traefik.http.middlewares.autodetect.contenttype.autodetect=false"
      - "traefik.http.routers.promenkul.middlewares=promenkul_compress"
      - "traefik.http.middlewares.limit.buffering.retryExpression=IsNetworkError() && Attempts() < 2"





networks:
  default:
    external:
      name: traefik_net