version: '3'

services:
  webserver:
    image: nginx
    volumes:
      - ./nginx/:/usr/share/nginx/html:ro
      - ./certbot/www/:/etc/nginx/ssl:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443